#define IDC_CHECKBOX_PORTABLEMODE               1000
#define IDC_CHECKBOX_CHECKNEWVERSION            1001
#define IDC_LABEL_LANGUAGE                      1002
#define IDC_EDIT_LANGUAGE                       1003
#define IDC_BUTTON_SHORTCUTONDESKTOP            1004
#define IDC_BUTTON_SHORTCUTINSTARTMENU          1005
#define IDC_CHECKBOX_MONITORCLIPBOARD           1006
#define IDC_CHECKBOX_DISABLEOPENSSLWARNING      1007

