{$INCLUDE '..\jedi.inc'}

{$DEFINE APIFORM_ANCHORS}
  // Allows easy resizing of forms through something similar to Delphi's anchors

{$DEFINE APIFORM_ACCELERATORS}
  // Allow accelerators (keyboard shortcuts)
  // Based on: http://us.generation-nt.com/answer/accellerators-modal-dialog-boxes-how-do-i-do-help-27734892.html

{$DEFINE APIFORM_TRANSLATIONS}
  // Allow automatic translations of the form after it is created

